{% set name = "Needle" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/seqan/needle/archive/refs/tags/needle-v{{ version }}.tar.gz
  sha256: ad616e4e95c8d7717343c955ee3d3d9a740f37786b5b58fcb5c2e676423daeb2

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - cmake >=3.8
  host:
    - bzip2
    - zlib
  run:
    - bzip2
    - zlib

test:
  commands:
    - needle --version
    - needle --help 2>&1 > /dev/null
    - needle count --help 2>&1 > /dev/null
    - needle ibf --help 2>&1 > /dev/null
    - needle ibfmin --help 2>&1 > /dev/null
    - needle minimiser --help 2>&1 > /dev/null
    - needle estimate --help 2>&1 > /dev/null

about:
  home: https://github.com/seqan/needle
  summary: "Needle: A fast and space-efficient pre-filter for the quantification of very large collections of nucleotide sequences"
  description: "Needle is a tool for approximately quantifiying many queries in large collections of nucleotide sequences."
  license: BSD-3-Clause License
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mitradarja
