{% set version = "0.1.1" %} 

package:
  name: chromap
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]

source:
  url: https://github.com/haowenz/chromap/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9aa0de8fe7f319b7411a085c1ae54ca48d8d55d5a01b022702fda4ab877c45c9

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - chromap --help

about:
  home: https://github.com/haowenz/chromap
  license: GPL-3.0
  license_file: LICENSE
  summary: Fast alignment and preprocessing of chromatin profiles
