{% set name = "slow5tools" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hasindu2008/slow5tools/releases/download/v0.3.0/slow5tools-v0.3.0-x86_64-linux-binaries.tar.gz
  sha256: 697e787e685f361792977463c90d54335351c8986e311b04c68f84653023e4ff

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - hdf5
    - wget
  run:
    - zlib
    - hdf5

test:
  commands:
    - slow5tools --help
    - slow5tools --version

about:
  home: https://github.com/hasindu2008/slow5tools
  license: MIT
  license_file: LICENSE
  summary: 'Slow5tools is a toolkit for converting (FAST5 <-> SLOW5), compressing, viewing, indexing and manipulating data in SLOW5 format.'
