{% set name = "miidl" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ff8795381abbe7dd992c9725ae6896756b08e0bd7d4f983cf17b01f69babb16
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv 

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytorch
    - torchvision
    - pandas

test:
  imports:
    - miidl
    
about:
  home: https://github.com/chunribu/miidl/
  license: MIT
  license_family: MIT
  summary: Python package for identification of biomarkers powered by interpretable Convolutional Neural Networks
  
extra:
  recipe-maintainers:
    - chunribu
